version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: pasteleria-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: BD_ProyectoPasteleria
      MYSQL_USER: pasteleria_user
      MYSQL_PASSWORD: pasteleria_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - pasteleria-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicación Spring Boot
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pasteleria-app
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Configuración de base de datos
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BD_ProyectoPasteleria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # Configuración JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      
      # Configuración del servidor
      SERVER_PORT: 8082
      
      # Configuración de archivos
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      
      # Perfil activo
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - app_uploads:/app/uploads
    networks:
      - pasteleria-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Adminer para administración de BD (opcional)
  adminer:
    image: adminer:4.8.1
    container_name: pasteleria-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - pasteleria-network
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
    driver: local
  app_uploads:
    driver: local

networks:
  pasteleria-network:
    driver: bridge